# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build_test_deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    # - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        # node-version: ${{ matrix.node-version }}
        node-version: 18.x
        cache: 'npm'
        
    - name: Install the app
      run: npm install
      
    - name: Start the App
      run: npm start &

    - name: Test the app
      run: npm test
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy for production
      uses: actions/checkout@v3
    - name: do deploy action
      uses: JorgeNLJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_TOKEN }}
        wait_deploy: true